### ISSUE TITLE
Dependency introduced a breaking change

### ISSUE THREAD

**Issue by qwerty01** [gluxon/wireguard-uapi-rs#11]
This package no longer compiles because `neli` version `0.4.4` introduced a change that is incompatible with version `0.4.3`.

A quick workaround is adding `neli = "=0.4.3"` to your Cargo.toml file before `wireguard-uapi` to force rust to use the previous version.

**Comment by qwerty01** [comment]
As a side note, I believe unignoring the Cargo.lock file would prevent a change like this from breaking the package in the future.

**Comment by gluxon** [comment]
> As a side note, I believe unignoring the Cargo.lock file would prevent a change like this from breaking the package in the future.

Yeah that makes sense. I went with the official recommendation from rust-lang.org but understand problems like this arise when packages don't follow semantic versioning.

https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries
