### ISSUE TITLE
WgSocket::get_device returns ParseDeviceError

### ISSUE THREAD

**Issue by dhl** [gluxon/wireguard-uapi-rs#9]
# Summary
wireguard-uapi (1.0.2) is unable to obtain device information for a device with 3 peers.

# Environment
wireguard-uapi version: v1.0.2
Operating System: Ubuntu 19.09
WireGuard version: v1.0.20200206

# Expected Behavior
```rust
wg.get_device(DeviceInterface::from_name("wg0"))
```
would return device information

# Actual Behavior
`WgSocket::getDevice` returns an `Err` with `parseDeviceError(UnknownDeviceAttributeError { id: 32776 })`

**Comment by gluxon** [comment]
Thanks for the report. I'll take a look this week.

**Comment by dhl** [comment]
Hi @gluxon. Further investigation shows that the unknown device attribute with ID 32776 is actually the peers attribute.

This is very perplexing. I really couldn't figure out why this is the case.

**Comment by dhl** [comment]
I am able to reproduce the same problem with neli, so it appears that it is a problem upstream.

**Comment by gluxon** [comment]
Ah, that's helpful to know. Were you able to reproduce it with one of neli's examples, or did you write a custom test case?

**Comment by dhl** [comment]
I basically followed what you did with wireguard-uapi to get device information confirm my hunch that the problem is with neli.

I tried https://git.zx2c4.com/wireguard-tools/tree/contrib/embeddable-wg-library and it was able to decode the attribute ID for peers just fine.

I suspect there's a decoding issue in neli's attribute decoding.

**Comment by dhl** [comment]
Hi @gluxon, it seems like the bug is due to `neli` not parsing the `nla_type` correctly.

I have reported the issue upstream https://github.com/jbaublitz/neli/issues/84

**Comment by gluxon** [comment]
I applied the new version of neli (`v0.5.0-rc1`) but discovered that the nested attributes flag needs to be set on netlink attribute types for Ubuntu 20.04 as well. The patch currently just masks it away for reading the type.

I was curious why the library works on Ubuntu 18.04 (the CI environment), and it looks like a Linux kernel commit in 2019 is the source of this change in behavior.

https://github.com/torvalds/linux/commit/ae0be8de9a53cda3505865c11826d8ff0640237c

Going to try always setting the flag on write and always masking it away on read. That behavior should be compatible with linux kernel versions before and after that patch but I'll have to test.

**Comment by gluxon** [comment]
This should be fixed in `v1.0.4`. Thanks for filing and deep diving to find the root issue David.

**Comment by dhl** [comment]
Thank you so much for this, Brandon!
